### ISSUE TITLE
Extend support of multiple microservices written on different languages

### ISSUE THREAD

**Issue by y0zg** [jonashackt/spring-boot-openapi-kong#22]
I'm curious about how the setup would look if we had multiple microservices, written in Java/Python, using OpenAPI. The idea is to automatically update the API gateway with the specifications from these OpenAPI microservices. Would it be possible to adapt current setup to accommodate this? Are there any potential drawbacks?

**Comment by jonashackt** [comment]
Hey, thats a broad question: just a small response: I think simply using the project 1:1 for each microservice would suffice, since I would recommend having a Git repository for every microservice. Than this would imply to have also a separate and central Kong instance, since otherwise you would have one Kong instance for every microservice (which is maybe not the idea of an API gateway). Having a central Kong instance (with Docker Compose or not) would bring the need to generate one big `kong.yml` configuration file featureing all OpenAPI service descriptions of all microservices as described in https://github.com/jonashackt/spring-boot-openapi-kong#generate-kong-declarative-config-from-openapi . This should be possible, but it would need some further investigation.
